### ISSUE TITLE
[Bug] Unable to shift click to select

### ISSUE THREAD

**Issue by ReddStrider** [arm32x/command-block-ide#63] opened 2024-10-21 05:00 UTC
(v0.4.10) I am unable to shift click to select from where my cursor is, to where I clicked. This is possible in any other text menu, including the command block menu without the mod.
This issue makes selecting parts of a command to copy-paste very tedious and breaks my workflow.

**Comment by arm32x** [comment] 2024-10-25 18:13
Duplicate of #41

**Closed as not planned by arm32x** 2024-10-25 18:13 UTC
Labels: bug, duplicate
